---
title: "Trabajo"
author: "Lic. Alvaro Chirino Gutierrez"
date: "20/5/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introdución

dfndsjkcbndcbdchbdsghcvdsghcvdsc
cdscdscsdcsdcs

# Objetivos

# Resultados

```{r eruptions, echo=FALSE}
inputPanel(
  numericInput("n","Cantidad de numeros aleatorios",value = 100),
  radioButtons("d","Seleccione la distribucion",c("Normal","Uniforme","Exponencial"))
)

 renderPlot({
        aux<-input$d
        if(aux=="Normal"){
            x<-rnorm(input$n)
        } else if(aux=="Uniforme"){
            x<-runif(input$n)
        } else if(aux=="Exponencial"){
            x<-rexp(input$n,5)
        }
        hist(x)
    })
 renderTable({
        aux<-input$d
        if(aux=="Normal"){
            x<-rnorm(input$n)
        } else if(aux=="Uniforme"){
            x<-runif(input$n)
        } else if(aux=="Exponencial"){
            x<-rexp(input$n,5)
        }
        matrix(x,nrow = 5)
    })
 renderPrint({
        aux<-input$d
        if(aux=="Normal"){
            x<-rnorm(input$n)
        } else if(aux=="Uniforme"){
            x<-runif(input$n)
        } else if(aux=="Exponencial"){
            x<-rexp(input$n,5)
        }
        summary(x)
    })
```

# Shiny 

```{r tabsets, echo=FALSE}
shinyAppDir("C:\\Users\\ALVARO\\Documents\\GitHub\\EST-383\\code\\shiny\\dist",
  options = list(
    width = "100%", height = 550
  )
)
```
