---
title: "Untitled"
author: "Alvaro Chirino"
date: "4/6/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r eruptions, echo=FALSE}
inputPanel(
  selectInput("n_breaks", label = "Number of bins:",
              choices = c(10, 20, 35, 50), selected = 20),
  
  sliderInput("bw_adjust", label = "Bandwidth adjustment:",
              min = 0.2, max = 2, value = 1, step = 0.2),
  actionButton("b1","Boton de acción"),
  checkboxInput("b2","Boton con opciones",2),
  textInput("b3","Boton de texto")
)

renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = input$b3)
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})


# renderImage(expr, env, quoted,deleteFile)
# renderPlot(expr, width, height, res, …,env, quoted, func)
# renderPrint(expr, env, quoted, func,width)
# renderTable(expr,…, env, quoted, func)
# renderText(expr, env, quoted, func)
# renderUI(expr, env, quoted, func)

```
