---
title: "Test auto diagnóstico"
subtitle: "Curso Básico de R"
author: "Alvaro Chirino Gutierrez"
date: "Julio, 2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Pregunta 1 

Escribir el código en R para los siguientes casos:

  * $\sum_{i=10}^{40}{\left(\frac{2^i}{i}+\frac{3^i}{i^2} \right)}$
  * Crear una matriz de $4*5$ que contengan valores aleatorios de una uniforme con $a=0, b=10$
  * Calcular $\sum_{i=1}^{20}{\sum_{j=2}^5{\frac{i^3}{2+ij}}}$
  * Crear una función que dado un vector numérico devuelva el coeficiente de variación y el coeficiente de asimetría de Pearson y Fisher.
  

## Pregunta 2
Usando la información de www.worldometers.info sobre el COVID con la librería rvest, generar:

  * Una tabla que muestre los 10 países con más altos contagios por millón
  * Un gráfico de los casos por millón ($X$) versus los test por millón ($Y$), incluir en el gráfico los nombres de los países.

## Pregunta 3 

Usando la encuesta de hogares defina una base de datos que contenga las siguientes variables para los jefes de hogar:

  + Edad
  + Sexo 
  + Ingreso laboral
  + Departamento 
  + Años de educación
  + Área
  + Incidencia de pobreza moderada (p0)
  + Acceso a internet en el hogar
  + Vivienda propia y totalmente pagada
  + Número de miembros en el hogar

(Sugerencia: Use la variable folio y el comando merge para unir bases)

Para la base creada, genere lo siguiente: 

  + Promedio de años de educación del jefe del hogar por departamento y Área 
  + Proporción de jefes del hogar con un ingreso laboral superior a 4000 Bs. Por Departamento y Sexo 
  + Proporción de pobreza moderada en hogares con jefes de hogar de 30 años o menos por sexo 
  + Promedio de miembros en el hogar por departamento, área y sexo del jefe del hogar
